---
title: "HBIC Scanlog"
date: "Generated `r format(Sys.time(), format = '%a %d %b %Y')`"
output: 
  html_document:
      toc: true
      toc_float: true
      toc_collapsed: true
      toc_depth: 3
      number_sections: true
      theme: lumen
params:
    ix_data: NA
    weekly_summary: NA
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
daydict <- c('Mon','Tues','Wed','Thur','Fri','Sat','Sun')
status_fields <- c('Project ID','Sched. / Actual','Status','Data')

text_green <- '#48E130'#'#3CA61C'
text_red <- '#E12A1B'
text_orange <- '#E1B730'

# Formatted text for table entries
ttext <- list(
  scanned = kableExtra::cell_spec('scanned', color = text_green),
  cancelled = kableExtra::cell_spec('cancelled', color = text_red),
  complete = kableExtra::cell_spec('complete', color = text_green),
  not_found =  kableExtra::cell_spec('not found', color = text_red),
  mismatch =  kableExtra::cell_spec('mismatch', color = text_orange)
  )


applyColor <- function(tt){
  text_green <- '#48E130'#'#3CA61C'
  text_red <- '#E12A1B'
  text_orange <- '#E1B730'
  format_tt <- tt
  if(any(grep('cancel',tolower(tt))) | any(grep('no show',tolower(tt))) ){
    format_tt <- kableExtra::cell_spec(tt, color = text_red)
  } else if(any(grep('complete',tt))){
    format_tt <- kableExtra::cell_spec(tt, color = text_green)
  } else if(any(grep('not_found',tt))){
    format_tt <- kableExtra::cell_spec(tt, color = text_red)
  } else if(any(grep('mismatch',tt))){
    format_tt <- kableExtra::cell_spec(tt, color = text_orange)
  } else if(any(grep('tbd',tt))){
    format_tt <- kableExtra::cell_spec(tt, color = text_orange)
  }
  
  return(format_tt)
}



```


```{r echo = FALSE}
#ix <- rbind(ix_data, ix_data)
#ix$studDesc[2] <- 'I put this here'
ix <- ix_data


print.days <- function(ix){
  printlines <- as.character()
  alldays <- unique(ix$studDate)
  for(day in alldays){
    printlines <- c(printlines,sprintf('DATE: %s',day))
    thisday <- subset(ix, studDate == day)
    for(line in 1:dim(thisday)[1]){
      scan_lines <-print.scan(thisday[line,])
      printlines <- c(printlines, scan_lines)
    }
      

  }
  return(printlines)
}

print.scan <- function(line){
  scan_lines <- c(
  sprintf('<b>%s</b>',line$studDesc),
  line$usage_type,
  sprintf('Scheduled: %s, Actual: %s', line$purchase_date_time, line$studDate_time_format),
  sprintf('Project ID: %s',line$study_id),
  sprintf('Scan ID: %s', line$patientID)
  )
  return(paste(scan_lines, collapse = '\n\n'))
}


```

# Weekly View


rmarkdown::render(system.file('extdata','report.Rmd', package = 'hbicScanLog'),
                   output_dir = getwd(),
                   output_file = 'test.html',
                   params = list(
                       ix_data = rbind(ix_data,ix_data),
                       weekly_summary = weekly_summary
                   ))


```{r echo=FALSE}


#sample data
#wk <- data.frame(day = c(1,1,2), id = c('101','202','101'), status = c(ttext$scanned,ttext$cancelled, ttext$scanned),dataset = c(ttext$complete, ttext$not_found, ttext$mismatch))

#wk <- rbind(weekly_summary,weekly_summary,weekly_summary)
#wk$dataset <- c('complete','not_found','mismatch')
#wk$usage_type <- unlist(lapply(wk$usage_type, applyColor))
#wk$dataset <- unlist(lapply(wk$dataset, applyColor))
 
wk <- weekly_summary
wk$dataset <- c('tbd')
wk$usage_type <- unlist(lapply(wk$usage_type, applyColor))
wk$dataset <- unlist(lapply(wk$dataset, applyColor))

# each list entry is a vector of all ID/status/data for all scans on that day.
# The list entries get cbinded together to create the output table
eachday <- list()
for(dd in 1:7){
  thisday <- subset(wk, day == dd) 
  eachday[[dd+1]] <- as.vector(t(thisday[,c(!colnames(thisday)%in% 'day')]))
}

# pad the shorter days with blank spaces so that columns can be bound
maxlines <- max(unlist(lapply(eachday,'length')))
for(dd in 1:7){
eachday[[dd+1]] <- c(eachday[[dd+1]], rep(' ', maxlines - length(eachday[[dd+1]])))
}
#First entry is the row names
eachday[[1]] <- rep(status_fields, maxlines/length(status_fields)) 

wk_summary <- as.data.frame(t(do.call('rbind',eachday)))
colnames(wk_summary) <- c('',daydict)


# Create table from dataframe. Add vertical columns between days, 
# and horizontal lines after each scan entry
hline_rows <- seq(from = length(status_fields), to = dim(wk_summary)[1]-1, by = length(status_fields))
wk_summary %>% 
knitr::kable(escape = FALSE)  %>%
kableExtra::column_spec (2:8,border_left = T, border_right = T) %>%
kableExtra::row_spec(hline_rows, extra_css = "border-bottom: 1px solid") %>%
kableExtra::kable_styling()

```

# Daily Summaries
```{r, echo = FALSE, results='asis'}



alldays <- unique(ix$purchase_date_day_posix)
for(day in sort(alldays)){
  thisday <- subset(ix, purchase_date_day_posix == day)
  dayweeknum <- as.numeric(strftime(as.POSIXct(day, origin = '1970-01-01'), format = '%u')) #1-7, monday is 1
  dayname <- daydict[dayweeknum]
  cat('##', dayname, strftime(as.POSIXct(day, origin = '1970-01-01'), format = '%m-%d-%Y'),'\n\n')

  thisday <- thisday[order(as.numeric(thisday$epoch)),]
  for(i in 1:dim(thisday)[1]){
    cat(print.scan(thisday[i,]),'\n\n')
  }
  
}


```

